name: Compress JavaScript

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  minify-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Terser
        run: npm install terser -g

      - name: Verify Terser Installation
        run: terser --version

      - name: Minify JavaScript
        run: |
          mkdir -p dist
          for file in src/*.js; do
            terser "$file" -o "dist/$(basename "$file" .js).min.js" --compress --mangle
          done

      - name: List Minified Files
        run: ls -lah dist

      - name: Force Commit Minified Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/*.js
          git diff --staged --quiet || git commit -m "Minify JavaScript files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
