name: Minify p-alo-script.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      # Step 3: Install terser globally
      - name: Install terser
        run: npm install -g terser

      # Step 4: Download the specific JavaScript file from GitHub
      - name: Download p-alo-script.js
        run: |
          mkdir -p src
          curl -L -o src/p-alo-script.js https://raw.githubusercontent.com/Kawaqdr/Nothing/main/p-alo-script.js

      # Step 5: Minify the downloaded JavaScript file
      - name: Minify p-alo-script.js
        run: |
          mkdir -p dist
          terser src/p-alo-script.js -o dist/p-alo-script.min.js -c -m

      # Step 6: Upload minified file as an artifact (optional)
      - name: Upload minified file
        uses: actions/upload-artifact@v3
        with:
          name: minified-p-alo-script
          path: dist/p-alo-script.min.js
